/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegmentsRouteImport } from './routes/segments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowsIndexRouteImport } from './routes/shows/index'
import { Route as ShowsShowIdRouteImport } from './routes/shows/$showId'
import { Route as ShowsShowIdPublishRouteImport } from './routes/shows/$showId.publish'

const SegmentsRoute = SegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIndexRoute = ShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowIdRoute = ShowsShowIdRouteImport.update({
  id: '/shows/$showId',
  path: '/shows/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowIdPublishRoute = ShowsShowIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => ShowsShowIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/segments': typeof SegmentsRoute
  '/shows/$showId': typeof ShowsShowIdRouteWithChildren
  '/shows': typeof ShowsIndexRoute
  '/shows/$showId/publish': typeof ShowsShowIdPublishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/segments': typeof SegmentsRoute
  '/shows/$showId': typeof ShowsShowIdRouteWithChildren
  '/shows': typeof ShowsIndexRoute
  '/shows/$showId/publish': typeof ShowsShowIdPublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/segments': typeof SegmentsRoute
  '/shows/$showId': typeof ShowsShowIdRouteWithChildren
  '/shows/': typeof ShowsIndexRoute
  '/shows/$showId/publish': typeof ShowsShowIdPublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/segments'
    | '/shows/$showId'
    | '/shows'
    | '/shows/$showId/publish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/segments'
    | '/shows/$showId'
    | '/shows'
    | '/shows/$showId/publish'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/segments'
    | '/shows/$showId'
    | '/shows/'
    | '/shows/$showId/publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SegmentsRoute: typeof SegmentsRoute
  ShowsShowIdRoute: typeof ShowsShowIdRouteWithChildren
  ShowsIndexRoute: typeof ShowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/segments': {
      id: '/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/': {
      id: '/shows/'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$showId': {
      id: '/shows/$showId'
      path: '/shows/$showId'
      fullPath: '/shows/$showId'
      preLoaderRoute: typeof ShowsShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$showId/publish': {
      id: '/shows/$showId/publish'
      path: '/publish'
      fullPath: '/shows/$showId/publish'
      preLoaderRoute: typeof ShowsShowIdPublishRouteImport
      parentRoute: typeof ShowsShowIdRoute
    }
  }
}

interface ShowsShowIdRouteChildren {
  ShowsShowIdPublishRoute: typeof ShowsShowIdPublishRoute
}

const ShowsShowIdRouteChildren: ShowsShowIdRouteChildren = {
  ShowsShowIdPublishRoute: ShowsShowIdPublishRoute,
}

const ShowsShowIdRouteWithChildren = ShowsShowIdRoute._addFileChildren(
  ShowsShowIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SegmentsRoute: SegmentsRoute,
  ShowsShowIdRoute: ShowsShowIdRouteWithChildren,
  ShowsIndexRoute: ShowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
