export const REACTIONABLE_TYPES = ["message", "track"];

export const FIVE_SECONDS = 1000 * 5;
export const TEN_SECONDS = 1000 * 10;
export const THREE_MINUTES = 1000 * 60 * 3;
export const FIVE_MINUTES = 1000 * 60 * 5;
export const FORTY_FIVE_MINS = 1000 * 60 * 45;
export const THREE_HOURS = 1000 * 60 * 60 * 3;
export const ONE_DAY = 1000 * 60 * 60 * 24;
export const THREE_DAYS = 1000 * 60 * 60 * 24 * 3;
export const SEVEN_DAYS = 1000 * 60 * 60 * 24 * 7;

export const FIFTEEN_MINUTES = 1000 * 60 * 15;

export const JUKEBOX_FETCH_INTERVAL = FIVE_SECONDS;
export const RADIO_FETCH_INTERVAL = FIVE_SECONDS;
export const THROTTLED_JUKEBOX_FETCH_INTERVAL = TEN_SECONDS;
export const ROOM_EXPIRE_TIME = ONE_DAY;
export const ROOM_IDLE_PAUSE_TIME = FIFTEEN_MINUTES;

export const ERROR_STATION_FETCH_FAILED = "Erorr: Failed to fetch station";

export const PUBSUB_ROOM_NOW_PLAYING_FETCHED = "ROOM:NOW_PLAYING_FETCHED";
export const PUBSUB_ROOM_DELETED = "ROOM:DELETED";
export const PUBSUB_USER_JOINED = "ROOM:USER_JOINED";
export const PUBSUB_ROOM_SETTINGS_UPDATED = "ROOM:SETTINGS_UPDATED";

export const PUBSUB_PLAYLIST_UPDATED = "PLAYLIST:UPDATED";
export const PUBSUB_PLAYLIST_ADDED = "PLAYLIST:ADDED";

// Service-agnostic error and authentication events
export const PUBSUB_METADATA_SOURCE_AUTH_ERROR = "ERROR:METADATA_SOURCE_AUTH";
export const PUBSUB_METADATA_SOURCE_RATE_LIMIT_ERROR = "ERROR:METADATA_SOURCE_RATE_LIMIT";
export const PUBSUB_PLAYBACK_STATE_CHANGED = "PLAYBACK:STATE_CHANGED";
export const PUBSUB_USER_SERVICE_ACCESS_TOKEN_REFRESHED = "SERVICE:USER_ACCESS_TOKEN_REFRESHED";
export const PUBSUB_USER_SERVICE_AUTHENTICATION_STATUS = "SERVICE:USER_AUTHENTICATION_STATUS";
export const PUBSUB_RADIO_ERROR = "ERROR:RADIO";

// Deprecated: Use service-agnostic constants above
/** @deprecated Use PUBSUB_METADATA_SOURCE_AUTH_ERROR */
export const PUBSUB_SPOTIFY_AUTH_ERROR = PUBSUB_METADATA_SOURCE_AUTH_ERROR;
/** @deprecated Use PUBSUB_METADATA_SOURCE_RATE_LIMIT_ERROR */
export const PUBSUB_SPOTIFY_RATE_LIMIT_ERROR = PUBSUB_METADATA_SOURCE_RATE_LIMIT_ERROR;
/** @deprecated Use PUBSUB_PLAYBACK_STATE_CHANGED */
export const PUBSUB_SPOTIFY_PLAYBACK_STATE_CHANGED = PUBSUB_PLAYBACK_STATE_CHANGED;
/** @deprecated Use PUBSUB_USER_SERVICE_ACCESS_TOKEN_REFRESHED */
export const PUBSUB_USER_SPOTIFY_ACCESS_TOKEN_REFRESHED = PUBSUB_USER_SERVICE_ACCESS_TOKEN_REFRESHED;
/** @deprecated Use PUBSUB_USER_SERVICE_AUTHENTICATION_STATUS */
export const PUBSUB_USER_SPOTIFY_AUTHENTICATION_STATUS = PUBSUB_USER_SERVICE_AUTHENTICATION_STATUS;
